services:
  midgard-node:
    build:
      context: .
      additional_contexts:
        - sdk=../midgard-sdk
      dockerfile: ./Dockerfile
    env_file:
      - .env
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    command:
      - node
      - ./dist/index.js
      - listen
    ports:
      - "3000:3000" # api server
    volumes:
      - ./db:/app/db
    depends_on:
      - postgres
    networks:
      midgard_net:

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    networks:
      midgard_net:

networks:
  midgard_net:

volumes:
  postgres-data:
    driver: local
