name = "al-ft/midgard"
version = "0.0.0"
compiler = "v1.1.19"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'al-ft/midgard'"

[repository]
user = "al-ft"
project = "midgard"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v3.0.0"
source = "github"

[[dependencies]]
name = "aiken-lang/fuzz"
version = "2.2.0"
source = "github"

[[dependencies]]
name = "anastasia-labs/aiken-design-patterns"
version = "v1.3.0"
source = "github"

[[dependencies]]
name = "keyan-m/aiken-scott-utils"
version = "v1.4.0"
source = "github"

[[dependencies]]
name = "aiken-lang/merkle-patricia-forestry"
version = "2.0.0"
source = "github"

[config]
